# Generated by Django 4.2.11 on 2024-05-04 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookmodel_image_alter_bookmodel_ebook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
    ]
